name: prayagedu
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gif: ^2.3.0
  convex_bottom_bar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/icons/add_icon.png
    - assets/icons/arrow.png
    - assets/icons/check.png
    - assets/icons/checkmark.png
    - assets/icons/cross.png
    - assets/icons/dot_green.png
    - assets/icons/dropdown.png
    - assets/icons/login_logo.png
    - assets/icons/home.png
    - assets/icons/school.png
    - assets/icons/school2.png
    - assets/icons/study.png
    - assets/icons/enter2.png
    - assets/icons/enter3.png
    - assets/icons/s2.png
    - assets/icons/otp3.png
    - assets/icons/email2.png
    - assets/icons/password.png
    - assets/icons/school2.gif
    - assets/icons/success.gif
    - assets/icons/loading.gif
    - assets/icons/loading2.gif
    - assets/icons/black_loading.gif
    - assets/icons/success2.gif
    - assets/icons/calender.png
    - assets/icons/fees.png
    - assets/icons/grievance.png
    - assets/icons/staff leave.png
    - assets/icons/notice.png
    - assets/icons/.pnprofileg

  uses-material-design: true

  fonts:
    - family: "Oswald_bold"
      fonts:
        - asset: assets/fonts/Oswald/static/Oswald-Bold.ttf

    - family: "Oswald_extra_light"
      fonts:
        - asset: assets/fonts/Oswald/static/Oswald-ExtraLight.ttf
